name: CI

on: [push]

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Gulp
        run: npm install -g gulp-cli

      - name: Install other dependencies
        run: npm install

      - name: Build
        run: gulp generic
      
      - name: Archive Release
        run: cd build/generic && zip -r pdfjs.zip ./  && cd -

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/generic/pdfjs.zip"
          tag: "latest"
          allowUpdates: true
